name: Blog
channels:
    - ioos
dependencies:
    - python=2.7
    - pelican=3.3
    - markdown=2.3.1
    - ipython-notebook=2.4.1
    - ghp-import
    - jinja2
    - markupsafe
    - pyyaml
    - pygments
    - unidecode
    - blinker
    - docutils
    - feedgenerator
    - pytz
    - pyzmq
    - six
    - tornado
    # Non-blog specific packages.
    - sympy
    - numpy
    - matplotlib
    - pandas
    - xlrd
    - gsw
    - ctd
    - oceans
    - ephem
    - statsmodels
    - jsanimation
    - folium
    - windspharm
    - palettable
    - simplekml
    - xarray
    - mplleaflet
    - geopandas
    - mpld3
    - bokeh
    - numba
